version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
      POSTGRES_DB: covid_data
    ports:
      - "5432:5432"
  data-loader:
    build: ./data-loader
    dependes_on:
      - db
